language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - mvn clean package -DskipTests

script:
  - echo "skip tests."

after_success:
  - docker build . -t jinjr/jinjr-server:$TRAVIS_COMMIT
  - docker push jinjr/jinjr-server:$TRAVIS_COMMIT

cache:
  directories:
  - .autoconf
  - $HOME/.m2

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: jinjr