language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mkdir ${HOME}/.kube
  - cp .kube/config ${HOME}/.kube/config
  - kubectl config set clusters.kubernetes-group-xxxxx.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
  - kubectl config set users.kubernetes-group-xxxxx-admin.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
  - kubectl config set users.kubernetes-group-xxxxx-admin.client-key-data "$KUBE_CLIENT_KEY"


install:
  - mvn clean package -DskipTests

script:
  - echo "skip tests."

after_success:
  - docker build . -t jinjr/jinjr-server:$TRAVIS_COMMIT
  - docker push jinjr/jinjr-server:$TRAVIS_COMMIT
  - kubectl rolling-update jinjr-server --image=jinjr/jinjr-server:$TRAVIS_COMMIT


cache:
  directories:
  - .autoconf
  - $HOME/.m2